### ISSUE TITLE
Shou

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum#378]
I'd like to introduce "shou", a tiny program I wrote to improve CI on atoum.

## The problem

Many projects depends on atoum, they use it to run their unit tests, they extend it, they reuse some code from it. To improve our contributions on atoum and avoid breaking stuff, we can use those projects to get more feedback on our code. In fact, many of them have unit tests we can run on atoum's pull-requests side-by-side with atoum own tests.

## How does it work

Given a pull-request is opened on `atoum/atoum` from `jubianchi/atoum`, shou will:

* clone `jubianchi/atoum`
* checkout the pull-request branch
* clone every project depending on atoum (from a list)
* run their tests using the atoum sources we just cloned

It will be triggered by a webhook on pull-requests and will answer with:

* commit statuses on the pull-request
* comments in pull-request with the build summary
* publish an html report with the build raw output

Here is a test PR : https://github.com/jubianchi/atoum/pull/14

## Roadmap

* [ ] Clean shou's code and improve its tests (WIP)
* [x] Open a repository: https://github.com/jubianchi/atoum-shou
* [ ] Push everything to it
* [ ] Migrate the repository to the atoum org.
* [ ] Add the repository to the Tools team
* [ ] Create a dedicated shou user
* [ ] Host shou (I have room for it on my server)
* [ ] Enable shou on atoum main repository
* [ ] Improve the list of tested repositories
* [ ] Improve shou (ignore non-relevant PRs, those who don't touch any PHP file, ...)

**Comment by Grummfy** [comment]
So except a documentation, is there anything missing?
