### ISSUE TITLE
Release 2.5.0

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum#546]
[What's left](https://github.com/atoum/atoum/milestones):

## Issues/PRs

* [x] #483 - Adopt the Open CoC: will be closed when #543 is merged
* [x] #539 - `$this->newMockInstance($class)`
* [x] #543 - Improve `CONTRIBUTING.md`
* [x] #547 `\DateTimeImmutable` assertions: will be closed when #548 is merged
* [x] #548 - The `dateTime` asserter now supports `\dateTimeImmutable` (PHP 5.5)
* [x] atoum/stubs#9 - Add stubs for iterator asserter
* [x] atoum/stubs#10 - Add stubs for the castToArray asserter and toArray methods
* [x] atoum/stubs#11 - Add stubs for the resource asserter

## Website

* [x] Cleanup
* [x] atoum/atoum.github.io#3 - Announce release in a blog post

@Hywan, @mikaelrandy if you see some tiny issues/PRs we can close before the release, fell free to add them here.

**Comment by Hywan** [comment]
@jubianchi Looks good for me, :+1: good job!

**Comment by mikaelrandy** [comment]
All is good for me too :+1:

**Comment by mikaelrandy** [comment]
Next release is planned for 15/01/2016, and christmas is 2 weeks ago. Do we still planned a "special christmas release" or do we wait for next standard release date ?

**Comment by jubianchi** [comment]
@mikaelrandy no need for a special release I think.

But [here](https://github.com/atoum/atoum/milestones) the 2.5.0 is planned for 07/01/2015. Is it ok ?

**Comment by mikaelrandy** [comment]
@jubianchi in my local planning, i have a reminder for 13/01, corresponding to friday, 6 weeks after last release (07/12).
I think this milestome was a mistake.

From a more objective point of view, this release contain lots of updates, and could be released this week, excepting if you want to finish some extra work.

**Comment by Hywan** [comment]
@mikaelrandy I have a reminder for the 15th of January :-p.

**Comment by mikaelrandy** [comment]
my bad, my reminder is for 15/01 too

**Comment by jubianchi** [comment]
@mikaelrandy feel free to postpone the github milestone if it does not match your schedule ;)

**Comment by mikaelrandy** [comment]
@jubianchi i think release content is more important than an empirical schedule ;)
So, do you need an extra week or not ?

**Comment by jubianchi** [comment]
@mikaelrandy no I don't need an extra week. I have to PR to close and everything should be fine. I'll try to finish them today

**Comment by mikaelrandy** [comment]
Okay, so we can close the milestone once all PRs will be merged

**Comment by Hywan** [comment]
:+1:

**Comment by jubianchi** [comment]
@atoum/rms here we go :) everything is ready for the release. Once the tag is online, you'll have to merge the post on the website ;)

**Comment by agallou** [comment]
and maybe tag some extensions between those two ?

**Comment by jubianchi** [comment]
@agallou yes yes :) extensions and stubs

**Comment by mikaelrandy** [comment]
@Hywan you assigned yourself to this issue. I let you release this version

**Comment by Hywan** [comment]
Ok. I am going to do this during my lunch break :-).

**Comment by Hywan** [comment]
Releasing!
