### ISSUE TITLE
Backport bugfixes from 3.0.0 to 2.x

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum#696]
* [x] #688 - Report: Avoid reporting incorrect atoum path
* [x] #690 - Fix appveyor build
* [x] #691 - Fix how annotations are extracted. Only those actually starting with `@` are handled
