### ISSUE TITLE
improve error reporting & readability

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#789]
A series of issue related to improvement of redability and undestanding:
- [ ] #777 PR to improve error displayed (ready)
- [ ] #764 issue reduce path to files to have a better view on errors
- [ ] #763 issue improve display of error
- [ ] #762 issue improve color scheme
- [ ] #797
- [ ] #806 

Globally:
* improve error message
* improve color schema
* improve error message on known issue
